// Package budget provides token and cost budget enforcement (ADR-008).
// The Governor checks available budget before each DAG node dispatch and
// records usage after completion.
package budget

import (
	"context"
	"errors"
	"time"
)

// BudgetStatus indicates whether the budget has capacity.
type BudgetStatus string

const (
	BudgetOK        BudgetStatus = "ok"
	BudgetExhausted BudgetStatus = "exhausted"
)

// Budget represents the current state of a budget.
type Budget struct {
	// OrgID identifies the tenant organization.
	OrgID string `json:"org_id"`

	// TokenCeiling is the maximum allowed tokens for the period.
	TokenCeiling int64 `json:"token_ceiling"`

	// TokenUsed is the tokens consumed so far.
	TokenUsed int64 `json:"token_used"`

	// TokenRemaining is the tokens still available.
	TokenRemaining int64 `json:"token_remaining"`

	// Status indicates whether the budget is OK or exhausted.
	Status BudgetStatus `json:"status"`

	// ResetAt is when the budget resets for the next period.
	ResetAt time.Time `json:"reset_at"`
}

// Usage records the cost of a single operation.
type Usage struct {
	// InputTokens consumed by the LLM request.
	InputTokens int `json:"input_tokens"`

	// OutputTokens generated by the LLM response.
	OutputTokens int `json:"output_tokens"`

	// AgentName identifies which agent consumed the tokens.
	AgentName string `json:"agent_name,omitempty"`
}

// TotalTokens returns the sum of input and output tokens.
func (u Usage) TotalTokens() int64 {
	return int64(u.InputTokens + u.OutputTokens)
}

// Governor enforces token and cost budgets. It must be checked before
// dispatching work and updated after completion.
type Governor interface {
	// Check verifies the budget has capacity for the given org.
	// Returns ErrBudgetExceeded when the ceiling is reached.
	Check(ctx context.Context, orgID string) (Budget, error)

	// Consume records token usage after a completed operation.
	Consume(ctx context.Context, orgID string, usage Usage) error
}

// Sentinel errors returned by Governor implementations.
var (
	ErrBudgetExceeded = errors.New("budget: exceeded")
)
